In [1]:
include("./param_discharge.jl");
include("./aux_functions_discharge.jl");

using Main.aux_functions
using Main.param
using ADCME
using SparseArrays

using DelimitedFiles
using Dates
using Plots

# definition of the parameters from the shell file
maxiter = 100
N_steps = 50
print("maximum iteration: ", maxiter, "\t", "Number of steps: ", N_steps, "\n")

# Definition of the parameters of initial descrite probabilities and initial lambda
global N_k_dis_ = 2
global T_exp = -3.0

# Initialization of the model and the optimization process


maximum iteration: 100	Number of steps: 50


2022-05-04 21:09:48.599640: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll


-3.0

In [2]:
param_model_val = param_model(N_steps = N_steps);


In [3]:
tf_variables, h_t, q_t_x, q_t_y = Darcy_flow_solver(param_model_val);

In [4]:
# model_param = param_model_val

# function P(h_, i, j)
#     # get the head for specifi i and j
#     tf.strided_slice(h_, [0, i + (j + 1) * model_param.N_y], [model_param.N_k, (j - 1) * model_param.N_y - 1], [1, model_param.N_y])
# end

# function P_y(h_, i, j)
#     # get the head for specifi i and j
#     tf.strided_slice(h_, [0, (i - 1) * model_param.N_x + 1 + j] , [model_param.N_k, i * model_param.N_x + j - 1], [1, 1])
# end

In [5]:
loss, dw_2, opt_ADAM, opt_LFGS, opt_ADAM_sum, opt_LFGS_sum, diff_eval, p_pre_soft_max, p, opt_LFGS_x = Info_upscale(tf_variables, param_model_val, q_t_x, q_t_y, N_k_dis_, maxiter)


C:\Users\dbeli\.julia\adcme\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
C:\Users\dbeli\.julia\adcme\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
C:\Users\dbeli\.julia\adcme\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
C:\Users\dbeli\.julia\adcme\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: U

(PyObject <tf.Tensor 'add_8:0' shape=() dtype=float64>, PyObject <tf.Tensor 'Mul_17:0' shape=() dtype=float64>, PyObject <tf.Operation 'Adam' type=NoOp>, PyObject <tensorflow.contrib.opt.python.training.external_optimizer.ScipyOptimizerInterface object at 0x0000000006EE88C8>, PyObject <tf.Operation 'Adam_1' type=NoOp>, PyObject <tensorflow.contrib.opt.python.training.external_optimizer.ScipyOptimizerInterface object at 0x000000009CE610C8>, PyObject <tf.Tensor 'Max_1:0' shape=() dtype=float64>, PyObject <tf.Variable 'Variable_3:0' shape=(1, 64) dtype=float64_ref>, PyObject <tf.Tensor 'Softmax:0' shape=(1, 64) dtype=float64>, PyObject <tensorflow.contrib.opt.python.training.external_optimizer.ScipyOptimizerInterface object at 0x000000009D0C2C48>)

In [5]:
sess = Session();
init(sess);


2022-05-04 20:52:48.938167: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2022-05-04 20:52:48.958505: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2022-05-04 20:52:49.081338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
2022-05-04 20:52:49.081793: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2022-05-04 20:52:49.122033: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2022-05-04 20:52:49.160546: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2022-05-04 20:52:49.172699: I tensorflow/stream_

In [6]:
check = aux_functions.IC()

PyObject <tf.Tensor 'Mul_10:0' shape=(64, 441) dtype=float64>

In [13]:
P(check,10,-1)

PyObject <tf.Tensor 'StridedSlice_10:0' shape=(64, 19) dtype=float64>

In [108]:
function P(h_, i, j)
    # get the head for specifi i and j
    tf.strided_slice(h_, [0, i - 1 + (j + 1) * model_param.N_y], [model_param.N_k, (j - 1) * model_param.N_y - 1], [1, model_param.N_y])
end

# function P_y(h_, i, j)
#     # get the head for specifi i and j
#     tf.strided_slice(h_, [0, (i - 1) * model_param.N_x + 1 + j], [model_param.N_k, i * model_param.N_x + j - 1], [1, 1])
# end


P (generic function with 1 method)

In [101]:
reshape(run(sess, check[1]), (21, 21))[ 1:9,:]

9×21 Matrix{Float64}:
 1.33702   1.32557   1.31365   1.30115   …  1.06784   1.05592   1.04447
 1.27016   1.25929   1.24797   1.23609      1.01445   1.00313   0.99225
 1.20331   1.19301   1.18229   1.17103      0.961055  0.950331  0.940027
 1.13646   1.12673   1.1166    1.10597      0.907663  0.897535  0.887803
 1.06961   1.06045   1.05092   1.04092      0.854272  0.844738  0.835579
 1.00276   0.994175  0.985238  0.97586   …  0.80088   0.791942  0.783356
 0.935911  0.927896  0.919555  0.910802     0.747488  0.739146  0.731132
 0.86906   0.861618  0.853873  0.845745     0.694096  0.68635   0.678908
 0.802209  0.79534   0.78819   0.780688     0.640704  0.633554  0.626684

In [92]:
reshape(run(sess, check[1]), (21, 21))[ 9:12,:]

4×21 Matrix{Float64}:
 0.802209  0.79534   0.78819   0.780688  …  0.640704  0.633554  0.626684
 0.735358  0.729061  0.722508  0.71563      0.587312  0.580758  0.574461
 0.668508  0.662783  0.656825  0.650573     0.53392   0.527962  0.522237
 0.601657  0.596505  0.591143  0.585516     0.480528  0.475165  0.470013

In [46]:
reshape(run(sess,check[1]),(21,21))[1,:][11]

1.1907447119661942

In [113]:
run(sess, P(check, 10, -1)[0])

19-element Vector{Float64}:
 0.7353584214460294
 0.7290614979466327
 0.7225075149831405
 0.7156303185853643
 0.7083589670521938
 0.700626327989149
 0.692383012781229
 0.6836157323327375
 0.6743659102241937
 0.6647409252187696
 0.6549095915814068
 0.645078257944044
 0.6354532729386199
 0.626203450830076
 0.6174361703815846
 0.6091928551736645
 0.6014602161106198
 0.5941888645774493
 0.5873116681796731

In [112]:
run(sess, P(check, 11,1)[0])

19-element Vector{Float64}:
 0.6568250136210368
 0.6505730168957857
 0.6439626973201762
 0.636933025444681
 0.6294391025283901
 0.6214688475752159
 0.6130599183856307
 0.6043099320170633
 0.5953723559830971
 0.586434779949131
 0.5776847935805636
 0.5692758643909782
 0.5613056094378042
 0.5538116865215132
 0.546782014646018
 0.5401716950704085
 0.5339196983451574
 0.5279615320147099
 0.5222370561061676

In [78]:
run(sess, P(check, 11, 1)[0])

19-element Vector{Float64}:
 0.5911425122589331
 0.585515715206207
 0.5795664275881585
 0.5732397229002129
 0.566495192275551
 0.5593219628176943
 0.5517539265470676
 0.5438789388153569
 0.5358351203847873
 0.5277913019542179
 0.5199163142225072
 0.5123482779518803
 0.5051750484940237
 0.4984305178693619
 0.49210381318141616
 0.4861545255633676
 0.4805277285106416
 0.47516537881323884
 0.4700133504955507

In [7]:
run(sess, h_t, feed_dict=Dict( tf_variables.N_k_dis => 4))

50×64×441 Array{Float64, 3}:
[:, :, 1] =
 1.33702  1.33702  1.33702  1.33702  …  1.33702  1.33702  1.33702  1.33702
 1.26669  1.26669  1.26669  1.26669     0.0      0.0      0.0      0.0
 1.23246  1.23246  1.23246  1.23246     0.0      0.0      0.0      0.0
 1.2158   1.2158   1.2158   1.2158      0.0      0.0      0.0      0.0
 1.20769  1.20769  1.20769  1.20769     0.0      0.0      0.0      0.0
 1.20374  1.20374  1.20374  1.20374  …  0.0      0.0      0.0      0.0
 1.20182  1.20182  1.20182  1.20182     0.0      0.0      0.0      0.0
 1.20089  1.20089  1.20089  1.20089     0.0      0.0      0.0      0.0
 1.20043  1.20043  1.20043  1.20043     0.0      0.0      0.0      0.0
 1.20021  1.20021  1.20021  1.20021     0.0      0.0      0.0      0.0
 1.2001   1.2001   1.2001   1.2001   …  0.0      0.0      0.0      0.0
 1.20005  1.20005  1.20005  1.20005     0.0      0.0      0.0      0.0
 1.20002  1.20002  1.20002  1.20002     0.0      0.0      0.0      0.0
 ⋮                              

In [9]:
run(sess, q_t_y, feed_dict=Dict( tf_variables.N_k_dis => 64))

50×64×1 Array{Float64, 3}:
[:, :, 1] =
 1.78446e-9   1.78886e-9   1.78672e-9   …  1.7896e-9    1.78526e-9
 1.49676e-9   1.49714e-9   1.49712e-9      1.50081e-9   1.49766e-9
 1.26821e-9   1.26926e-9   1.27041e-9      1.26941e-9   1.27005e-9
 1.09517e-9   1.09504e-9   1.09264e-9      1.09418e-9   1.09342e-9
 9.65679e-10  9.65896e-10  9.65179e-10     9.6657e-10   9.66359e-10
 8.77985e-10  8.76135e-10  8.78389e-10  …  8.75583e-10  8.78554e-10
 8.14132e-10  8.15459e-10  8.14342e-10     8.14065e-10  8.1502e-10
 7.73214e-10  7.7307e-10   7.73864e-10     7.72271e-10  7.71931e-10
 7.43292e-10  7.42837e-10  7.44792e-10     7.43082e-10  7.42776e-10
 7.24654e-10  7.25112e-10  7.23751e-10     7.25066e-10  7.23491e-10
 7.09857e-10  7.09883e-10  7.11603e-10  …  7.11277e-10  7.10745e-10
 7.01673e-10  7.02509e-10  7.01026e-10     7.00794e-10  7.01733e-10
 6.93937e-10  6.94667e-10  6.94319e-10     6.9557e-10   6.94856e-10
 ⋮                                      ⋱               
 6.80771e-10  6.81679e-10

In [21]:
loss, dw_2, opt_ADAM, opt_LFGS, opt_ADAM_sum, opt_LFGS_sum, diff_eval, p_pre_soft_max, p, opt_LFGS_x = Info_upscale(tf_variables, param_model_val, q_t_x, N_k_dis_, maxiter)


(PyObject <tf.Tensor 'Mul_23:0' shape=() dtype=float64>, PyObject <tf.Tensor 'Mul_21:0' shape=() dtype=float64>, PyObject <tf.Operation 'Adam' type=NoOp>, PyObject <tensorflow.contrib.opt.python.training.external_optimizer.ScipyOptimizerInterface object at 0x00000000A2514748>, PyObject <tf.Operation 'Adam_1' type=NoOp>, PyObject <tensorflow.contrib.opt.python.training.external_optimizer.ScipyOptimizerInterface object at 0x000000018E65E308>, PyObject <tf.Tensor 'Max_1:0' shape=() dtype=float64>, PyObject <tf.Variable 'Variable_6:0' shape=(1, 64) dtype=float64_ref>, PyObject <tf.Tensor 'Softmax:0' shape=(1, 64) dtype=float64>, PyObject <tensorflow.contrib.opt.python.training.external_optimizer.ScipyOptimizerInterface object at 0x000000018E6D11C8>)