In [1]:
include("./param.jl");
include("./multi_k_solver.jl");

using Main.multi_k_solver
using Main.param
using ADCME
using SparseArrays

using DelimitedFiles
using Dates
using Plots

2021-12-08 19:45:30.766406: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll


In [2]:
# definition of the parameters from the shell file
maxiter = 200
N_steps = 50
print("maximum iteration: ",maxiter,"\t","Number of steps: ",N_steps,"\n")

# Definition of the parameters of initial descrite probabilities and initial lambda
global N_k_dis_ = 2
global T_exp = -3.0

maximum iteration: 200	Number of steps: 50


-3.0

In [3]:

model_param = param_model(N_k = 64, N_x = 10, N_y = 10, N_steps = 50);


In [4]:
constant(0)

PyObject <tf.Tensor 'Const_1:0' shape=() dtype=int64>

In [5]:
tf_variables, check_h, q_t = solver_multi_k(model_param)


(Main.multi_k_solver.tf_variables_definition(PyObject <tf.Tensor 'PlaceholderWithDefault_2:0' shape=(1,) dtype=float64>, PyObject <tf.Tensor 'PlaceholderWithDefault_1:0' shape=() dtype=int32>, PyObject <tf.Tensor 'stack_4:0' shape=(2, 50, 1, 1, 1) dtype=float64>, PyObject <tf.Tensor 'Exp:0' shape=(50, 64, 10, 10) dtype=float64>, PyObject <tf.Variable 'Variable:0' shape=(50, 1, 1, 1) dtype=float64_ref>, PyObject <tf.Variable 'Variable_1:0' shape=(50, 1, 1, 1) dtype=float64_ref>), PyObject <tf.Tensor 'TensorArrayStack/TensorArrayGatherV3:0' shape=(50, 64, 100) dtype=float64>, PyObject <tf.Tensor 'truediv_6:0' shape=(50, 64) dtype=float64>)

In [6]:
loss, dw_2_sum, opt_ADAM, opt_LFGS, opt_ADAM_sum, opt_LFGS_sum, diff_eval, p_pre_soft_max, p = Info_upscale(tf_variables, model_param, q_t)

C:\Users\dbeli\.julia\adcme\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
C:\Users\dbeli\.julia\adcme\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
C:\Users\dbeli\.julia\adcme\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
C:\Users\dbeli\.julia\adcme\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: U

(PyObject <tf.Tensor 'truediv_11:0' shape=() dtype=float64>, PyObject <tf.Tensor 'Mul_6:0' shape=() dtype=float64>, PyObject <tf.Operation 'Adam' type=NoOp>, PyObject <tensorflow.contrib.opt.python.training.external_optimizer.ScipyOptimizerInterface object at 0x000000009966D588>, PyObject <tf.Operation 'Adam_1' type=NoOp>, PyObject <tensorflow.contrib.opt.python.training.external_optimizer.ScipyOptimizerInterface object at 0x000000009D5869C8>, PyObject <tf.Tensor 'Max_1:0' shape=() dtype=float64>, PyObject <tf.Variable 'Variable_2:0' shape=(1, 64) dtype=float64_ref>, PyObject <tf.Tensor 'Softmax:0' shape=(1, 64) dtype=float64>)

In [11]:
q_t

LoadError: UndefVarError: q_t not defined

In [6]:
# Initialization of the session
sess = Session();
init(sess);


# Initial lambda
T_ = 10.0 .^ -T_exp





2021-12-02 19:11:34.776814: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-12-02 19:11:34.781286: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-12-02 19:11:34.805910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
2021-12-02 19:11:34.805933: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2021-12-02 19:11:34.808546: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2021-12-02 19:11:34.810940: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2021-12-02 19:11:34.811913: I tensorflow/stream_

1000.0

In [10]:
p

PyObject <tf.Tensor 'Softmax:0' shape=(1, 64) dtype=float64>

In [8]:
run(sess,tf_variables.K)

64×10×10 Array{Float64, 3}:
[:, :, 1] =
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5  …  1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5     1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5     1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5     1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5     1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5  …  1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5     1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5     1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5     1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5     1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5  …  1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5     1.0e-5  1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5  1.0e-5  1.0e-5     1.0e-5  1.0e-5  

In [12]:
# Save values of the initial guess
# save_values(sess, model_param, tf_variables, q_t, p, T_exp)
print_status(sess, model_param, loss, diff_eval, T_exp, T_, 5, tf_variables, "w")

Saving Values at: 19:14-3.0	1000.0	0.0	0.05018787902574411		5


In [13]:
run(sess, diff_eval, feed_dict = Dict(tf_variables.lambda => ones(1) * 1, tf_variables.N_k_dis => 4))

0.0

In [13]:
run(sess, diff_eval, feed_dict = Dict(tf_variables.lambda => ones(1) * 1, tf_variables.N_k_dis => 64))

0.0

In [21]:
sort_list = tf.sort(q_t, axis = 1)

PyObject <tf.Tensor 'sort_2/Neg_1:0' shape=(50, 64) dtype=float64>

In [35]:
tf_variables.N_k_dis

PyObject <tf.Tensor 'PlaceholderWithDefault_1:0' shape=() dtype=int32>

In [19]:
check = tf.slice(sort_list[1], [0, 0], [-1, tf_variables.N_k_dis - 1])

PyObject <tf.Tensor 'Slice_4:0' shape=(?, ?) dtype=float64>

In [16]:
    sort_list = [tf.sort(q_t, axis = 1)]
    diff_list = [tf.reduce_max(tf.reduce_min((tf.slice(sort_list[ii], [0, 1], [-1, -1]) -
                                              (tf.slice(sort_list[ii], [0, 0], [-1, tf_variables.N_k_dis - 1]))) ./ tf.reduce_mean(sort_list[ii], axis = 1, keep_dims = true), axis = 1)) for ii in 1]
    # diff_eval = tf.reduce_max(tf.stack(diff_list))

0-dimensional Array{PyCall.PyObject, 0}:
PyObject <tf.Tensor 'Max_2:0' shape=() dtype=float64>

In [24]:
diff_ = run(sess, check, feed_dict = Dict(tf_variables.N_k_dis => 64))


50×63 Matrix{Float64}:
 1.1e-8      1.1e-8      1.1e-8      …  1.1e-8      1.1e-8      1.1e-8
 1.09701e-8  1.09701e-8  1.09701e-8     1.09701e-8  1.09701e-8  1.09701e-8
 1.09074e-8  1.09074e-8  1.09074e-8     1.09074e-8  1.09074e-8  1.09074e-8
 1.08235e-8  1.08235e-8  1.08235e-8     1.08235e-8  1.08235e-8  1.08235e-8
 1.07307e-8  1.07307e-8  1.07307e-8     1.07307e-8  1.07307e-8  1.07307e-8
 1.06382e-8  1.06382e-8  1.06382e-8  …  1.06382e-8  1.06382e-8  1.06382e-8
 1.05513e-8  1.05513e-8  1.05513e-8     1.05513e-8  1.05513e-8  1.05513e-8
 1.04725e-8  1.04725e-8  1.04725e-8     1.04725e-8  1.04725e-8  1.04725e-8
 1.04028e-8  1.04028e-8  1.04028e-8     1.04028e-8  1.04028e-8  1.04028e-8
 1.03421e-8  1.03421e-8  1.03421e-8     1.03421e-8  1.03421e-8  1.03421e-8
 1.02897e-8  1.02897e-8  1.02897e-8  …  1.02897e-8  1.02897e-8  1.02897e-8
 1.02449e-8  1.02449e-8  1.02449e-8     1.02449e-8  1.02449e-8  1.02449e-8
 1.02068e-8  1.02068e-8  1.02068e-8     1.02068e-8  1.02068e-8  1.02068e-8
 ⋮    

In [31]:
diff_[1]

50×64 Matrix{Float64}:
 1.1e-8  1.1e-8  1.1e-8  1.1e-8  …  1.1e-8      1.1e-8      1.1e-8
 0.0     0.0     0.0     0.0        1.09701e-8  1.09701e-8  1.09701e-8
 0.0     0.0     0.0     0.0        1.09074e-8  1.09074e-8  1.09074e-8
 0.0     0.0     0.0     0.0        1.08235e-8  1.08235e-8  1.08235e-8
 0.0     0.0     0.0     0.0        1.07307e-8  1.07307e-8  1.07307e-8
 0.0     0.0     0.0     0.0     …  1.06382e-8  1.06382e-8  1.06382e-8
 0.0     0.0     0.0     0.0        1.05513e-8  1.05513e-8  1.05513e-8
 0.0     0.0     0.0     0.0        1.04725e-8  1.04725e-8  1.04725e-8
 0.0     0.0     0.0     0.0        1.04028e-8  1.04028e-8  1.04028e-8
 0.0     0.0     0.0     0.0        1.03421e-8  1.03421e-8  1.03421e-8
 0.0     0.0     0.0     0.0     …  1.02897e-8  1.02897e-8  1.02897e-8
 0.0     0.0     0.0     0.0        1.02449e-8  1.02449e-8  1.02449e-8
 0.0     0.0     0.0     0.0        1.02068e-8  1.02068e-8  1.02068e-8
 ⋮                               ⋱                        

In [13]:
ScipyOptimizerMinimize(sess, opt_LFGS_sum, feed_dict = Dict(tf_variables.lambda => ones(1) * T_, tf_variables.N_k_dis => 4))


In [11]:
K_log = Variable(ones(model_param.N_k, 1, 1) * 1e-5)
K_log_field = K_log .* ones(1, model_param.N_x, model_param.N_y)

PyObject <tf.Tensor 'Mul_4:0' shape=(2, 10, 10) dtype=float64>

In [ ]:


K_log = Variable(log.(ones(model_param.N_k, model_param.N_x, model_param.N_y) * 1e-5))


In [15]:
sess = Session(); init(sess);


2021-11-30 22:38:36.492174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
2021-11-30 22:38:36.492203: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2021-11-30 22:38:36.492249: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2021-11-30 22:38:36.492256: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2021-11-30 22:38:36.492263: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2021-11-30 22:38:36.492269: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2021-11-30 22:38:36.492275: I tensorflow/stream_executor/platform

In [18]:
run(sess, dw_2_sum)

5.01878790257441e6

In [13]:
check_q

PyObject <tf.Tensor 'truediv_6:0' shape=(50, 2) dtype=float64>

In [16]:
K_log = Variable(log.(ones(model_param.N_k, 1, 1) * 1e-5))
K_log_field = K_log .* ones(1, model_param.N_x, model_param.N_y)
K = tf.exp(K_log_field)

PyObject <tf.Tensor 'Exp_2:0' shape=(2, 10, 10) dtype=float64>